apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: numerus-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: numerus-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 50
